name: Continuous Integration and Delivery with GitHub Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_MYSQL_PASSWORD }}
          MYSQL_DATABASE: books_management_system
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Login to Google Cloud Platform
      uses: 'google-github-actions/auth@v3'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v4
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
#
#    - name: Login to Amazon ECR
#      id: login-ecr
#      uses: aws-actions/amazon-ecr-login@v2

    - name: Configure Docker Authentication for Google Cloud Artifact Registry
      run: gcloud auth configure-docker ${{ secrets.GOOGLE_PKG }}

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Build Application .jar
      working-directory: ./
      env:
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        DB_MYSQL_PASSWORD: ${{ secrets.DB_MYSQL_PASSWORD }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

#    - name: Tag and Push to Docker Image to Amazon Container Registry - ECR
#      run: |
#        docker tag ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest ${{ secrets.IMAGE_REPO_URL }}:latest
#        docker tag ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}
#
#        docker push ${{ secrets.IMAGE_REPO_URL }}:latest
#        docker push ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}

#    - name: Download task definition
#      run: |
#        aws ecs describe-task-definition --task-definition ${{ secrets.TASK_DEFINITION_NAME }} --query taskDefinition > task-definition.json
#
#    - name: Fill in the new image ID in the Amazon ECS task definition
#      id: task-def
#      uses: aws-actions/amazon-ecs-render-task-definition@v1
#      with:
#        task-definition: task-definition.json
#        container-name: ${{ secrets.CONTAINER_NAME }}
#        image: ${{ secrets.IMAGE_REPO_URL }}:latest
#
#    - name: Deploy Amazon ECS task definition
#      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
#      with:
#        task-definition: ${{ steps.task-def.outputs.task-definition }}
#        service: ${{ secrets.SERVICE_NAME}}
#        cluster: ${{ secrets.CLUSTER_NAME }}
#        wait-for-service-stability: true

    - name: Push to Google Cloud Artifact Registry
      run: |       
        docker tag ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest ${{ secrets.REGISTRY_INFO }}/books-management-system:latest
        docker tag ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest ${{ secrets.REGISTRY_INFO }}/books-management-system:${{ github.run_id }}
        
        docker push ${{ secrets.REGISTRY_INFO }}/books-management-system:latest
        docker push ${{ secrets.REGISTRY_INFO }}/books-management-system:${{ github.run_id }}

#    - name: Deploy to Google Cloud Run
#      run: |
#        gcloud run deploy books-management-system \
#          --image ${{ secrets.REGISTRY_INFO }}/books-management-system:latest \
#          --region europe-west1 \
#          --platform managed \
#          --allow-unauthenticated

    - name: Push to Docker Hub Container
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest ${{ secrets.DOCKER_USERNAME }}/books-management-system:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/books-management-system:${{ github.run_id }}