name: Continuous Integration and Delivery with GitHub Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_MYSQL_PASSWORD }}
          MYSQL_DATABASE: books_management_system
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v4
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
#
#    - name: Login to Amazon ECR
#      id: login-ecr
#      uses: aws-actions/amazon-ecr-login@v2

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Build Application .jar
      working-directory: ./
      env:
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        DB_MYSQL_PASSWORD: ${{ secrets.DB_MYSQL_PASSWORD }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

#    - name: Tag and Push to Docker Image to Amazon Container Registry - ECR
#      run: |
#        docker tag ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest ${{ secrets.IMAGE_REPO_URL }}:latest
#        docker tag ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}
#
#        docker push ${{ secrets.IMAGE_REPO_URL }}:latest
#        docker push ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}

    - name: Push to Docker Hub Container
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest ${{ secrets.DOCKER_USERNAME }}/books-management-system:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/books-management-system:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/books-management-system:${{ github.run_id }}